import type { Metadata } from "next";
import { Geist_Mono, IBM_Plex_Sans, Syne } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { LayoutContent } from "./layout-content";

const syne = Syne({ subsets: ["latin"], variable: "--font-heading" });

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistMono.variable,
        "font-sans",
        ibmPlexSans.variable,
        syne.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
